name: Docker Image CI / CD


on:
  push:
    branches:
      - dev*


jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/${{ github.repository }}/ansible-linter:develop
    - name: Docker login
      run: echo $GITHUBTOKEN | docker login docker.pkg.github.com --username ${{github.actor}} --password-stdin
      env:
        GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}
    - name: Push Docker image to Github package registry
      run: docker push docker.pkg.github.com/${{ github.repository }}/ansible-linter:develop